/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pa_2019_01_23_aplicacioncilindrovisual;

import java.awt.Color;
import java.util.Random;

/**
 *
 * @author aa533
 */
public class JframePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JframePrincipal
     */
    public JframePrincipal() {
        initComponents();
        
        jButtObjeto.setText("Objeto");
    }
    public double volumenCilindro(double radio, double altura){
        double volumen=0;
        volumen = Math.PI * Math.pow(radio, 2) * altura;
        return volumen;
    }
    public double areaCilindro(double radio, double altura){
        return 2 * Math.PI * radio * (radio+altura);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextRadio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextAltura = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabArea = new javax.swing.JLabel();
        jLabVolumen = new javax.swing.JLabel();
        jButtCalcular = new javax.swing.JButton();
        jButtBorrar = new javax.swing.JButton();
        jButtAleatorios = new javax.swing.JButton();
        jButtFunciones = new javax.swing.JButton();
        jButtObjeto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Radio");

        jLabel2.setText("Altura");

        jLabel3.setText("Area");

        jLabel4.setText("Volumen");

        jLabArea.setBackground(java.awt.Color.cyan);
        jLabArea.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabArea.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabArea.setOpaque(true);

        jLabVolumen.setBackground(java.awt.Color.cyan);
        jLabVolumen.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabVolumen.setOpaque(true);

        jButtCalcular.setBackground(new java.awt.Color(255, 255, 102));
        jButtCalcular.setText("Calcular");
        jButtCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtCalcularActionPerformed(evt);
            }
        });

        jButtBorrar.setText("Borrar");
        jButtBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtBorrarActionPerformed(evt);
            }
        });

        jButtAleatorios.setText("Aleatorios");
        jButtAleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtAleatoriosActionPerformed(evt);
            }
        });

        jButtFunciones.setBackground(new java.awt.Color(51, 255, 51));
        jButtFunciones.setText("Funciones");
        jButtFunciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtFuncionesActionPerformed(evt);
            }
        });

        jButtObjeto.setBackground(new java.awt.Color(102, 102, 255));
        jButtObjeto.setText("jButton1");
        jButtObjeto.setOpaque(false);
        jButtObjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtObjetoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtCalcular))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabArea, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                    .addComponent(jLabVolumen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtObjeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtAleatorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtFunciones)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtAleatorios)
                    .addComponent(jButtFunciones))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtObjeto))
                        .addGap(45, 45, 45)
                        .addComponent(jLabel3)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabArea, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabVolumen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtBorrar)
                    .addComponent(jButtCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtCalcularActionPerformed
        // TODO add your handling code here:
        double radio, altura , area, volumen;
       // radio = jTextRadio.getText();
        radio = Double.parseDouble(jTextRadio.getText());
        altura = Double.parseDouble(jTextAltura.getText());
        
        volumen = Math.PI*Math.pow(radio, 2)*altura;
        area = 2*Math.PI*radio*(radio+altura);
        
        jLabArea.setText(area+"");
        jLabVolumen.setText(volumen+"");
        
        //Cambiar color
        jLabArea.setBackground(jButtCalcular.getBackground());
        jLabVolumen.setBackground(jButtCalcular.getBackground());
        
        
      
        
    }//GEN-LAST:event_jButtCalcularActionPerformed

    private void jButtBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtBorrarActionPerformed
        // TODO add your handling code here:
        
        jTextRadio.setText("");
        jTextAltura.setText("");
        jLabArea.setText("");
        jLabVolumen.setText("");
        
        jLabArea.setBackground(Color.CYAN);
        jLabVolumen.setBackground(Color.CYAN);
    }//GEN-LAST:event_jButtBorrarActionPerformed

    private void jButtAleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtAleatoriosActionPerformed
        // TODO add your handling code here:
        Random azar = new Random();
        
        jTextRadio.setText(azar.nextInt(101)/10.0+"");
        jTextAltura.setText(azar.nextInt(501)/10.0+"");
        jLabArea.setText("");
        jLabVolumen.setText("");
        
        
    }//GEN-LAST:event_jButtAleatoriosActionPerformed

    private void jButtFuncionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtFuncionesActionPerformed
        // TODO add your handling code here:
        double radio, altura , area, volumen;
       // radio = jTextRadio.getText();
        radio = Double.parseDouble(jTextRadio.getText());
        altura = Double.parseDouble(jTextAltura.getText());
        
        //Proceso y salida
        jLabArea.setText(areaCilindro(radio,altura)+"");
        jLabVolumen.setText(volumenCilindro(radio,altura)+"");
        
        //Cambiar colores
        jLabArea.setBackground(jButtFunciones.getBackground());
        jLabVolumen.setBackground(jButtFunciones.getBackground());
    }//GEN-LAST:event_jButtFuncionesActionPerformed

    private void jButtObjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtObjetoActionPerformed
        // TODO add your handling code here:
        double radio = Double.parseDouble(jTextRadio.getText());
        double altura = Double.parseDouble(jTextAltura.getText());
        
        Cilindro x = new Cilindro(radio,altura);
        //Proceso y salida
        jLabArea.setText(x.area()+"");
        jLabVolumen.setText(x.volumen()+"");
        
        //Cambiar colores
        jLabArea.setBackground(jButtObjeto.getBackground());
        jLabVolumen.setBackground(jButtObjeto.getBackground());
                                                 
    }//GEN-LAST:event_jButtObjetoActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JframePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JframePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JframePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JframePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JframePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtAleatorios;
    private javax.swing.JButton jButtBorrar;
    private javax.swing.JButton jButtCalcular;
    private javax.swing.JButton jButtFunciones;
    private javax.swing.JButton jButtObjeto;
    private javax.swing.JLabel jLabArea;
    private javax.swing.JLabel jLabVolumen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextAltura;
    private javax.swing.JTextField jTextRadio;
    // End of variables declaration//GEN-END:variables
}
