/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pa_2019_02_01_aplicacionalumnosvisual;

import java.util.Random;
import java.text.DecimalFormat;

/**
 *
 * @author aa531
 */
public class JframePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JframePrincipal
     */
    public JframePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextAlumno1 = new javax.swing.JTextField();
        jTextTareas1 = new javax.swing.JTextField();
        jTextProyectos1 = new javax.swing.JTextField();
        jTextExamen1 = new javax.swing.JTextField();
        jTextAsist1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabCalif1 = new javax.swing.JLabel();
        jTextAlumno2 = new javax.swing.JTextField();
        jTextTareas2 = new javax.swing.JTextField();
        jTextProyectos2 = new javax.swing.JTextField();
        jTextExamen2 = new javax.swing.JTextField();
        jLabCalif2 = new javax.swing.JLabel();
        jTextAsist2 = new javax.swing.JTextField();
        jTextAlumno3 = new javax.swing.JTextField();
        jTextTareas3 = new javax.swing.JTextField();
        jTextProyectos3 = new javax.swing.JTextField();
        jTextExamen3 = new javax.swing.JTextField();
        jLabCalif3 = new javax.swing.JLabel();
        jTextAsist3 = new javax.swing.JTextField();
        jLabPromCalif = new javax.swing.JLabel();
        jLabPromExamen = new javax.swing.JLabel();
        jLabPromPoyectos = new javax.swing.JLabel();
        jLabPromTareas = new javax.swing.JLabel();
        jLabPromAsist = new javax.swing.JLabel();
        jButCalcular = new javax.swing.JButton();
        jButAleatorios = new javax.swing.JButton();
        jButBorrar = new javax.swing.JButton();
        jLabMejor = new javax.swing.JLabel();

        jLabel15.setText("Examen");

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        jLabel16.setText("Calificacion");

        jLabel17.setBackground(new java.awt.Color(204, 255, 204));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setOpaque(true);

        jLabel18.setText("Alumno");

        jLabel19.setText("Asist");

        jLabel20.setText("Tareas");

        jLabel21.setText("Proytectos");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextAlumno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextAlumno1ActionPerformed(evt);
            }
        });

        jTextTareas1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextProyectos1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextExamen1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextAsist1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel1.setText("Alumno");

        jLabel2.setText("Asist");

        jLabel3.setText("Tareas");

        jLabel4.setText("Proyectos");

        jLabel5.setText("Examen");

        jLabel6.setText("Calificacion");

        jLabCalif1.setBackground(new java.awt.Color(204, 255, 204));
        jLabCalif1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabCalif1.setOpaque(true);

        jTextAlumno2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextAlumno2ActionPerformed(evt);
            }
        });

        jTextTareas2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextProyectos2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextExamen2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabCalif2.setBackground(new java.awt.Color(204, 255, 204));
        jLabCalif2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabCalif2.setOpaque(true);

        jTextAsist2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextAlumno3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextAlumno3ActionPerformed(evt);
            }
        });

        jTextTareas3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextProyectos3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jTextExamen3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabCalif3.setBackground(new java.awt.Color(204, 255, 204));
        jLabCalif3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabCalif3.setOpaque(true);

        jTextAsist3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabPromCalif.setBackground(new java.awt.Color(102, 204, 255));
        jLabPromCalif.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabPromCalif.setOpaque(true);

        jLabPromExamen.setBackground(new java.awt.Color(102, 204, 255));
        jLabPromExamen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabPromExamen.setOpaque(true);

        jLabPromPoyectos.setBackground(new java.awt.Color(102, 204, 255));
        jLabPromPoyectos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabPromPoyectos.setOpaque(true);

        jLabPromTareas.setBackground(new java.awt.Color(102, 204, 255));
        jLabPromTareas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabPromTareas.setOpaque(true);

        jLabPromAsist.setBackground(new java.awt.Color(102, 204, 255));
        jLabPromAsist.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabPromAsist.setOpaque(true);

        jButCalcular.setText("Calcular");
        jButCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCalcularActionPerformed(evt);
            }
        });

        jButAleatorios.setText("Aleatorios");
        jButAleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAleatoriosActionPerformed(evt);
            }
        });

        jButBorrar.setText("Borrar");
        jButBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButBorrarActionPerformed(evt);
            }
        });

        jLabMejor.setBackground(new java.awt.Color(255, 255, 204));
        jLabMejor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabMejor.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextAlumno1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextTareas1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabPromAsist, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jTextAsist1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jTextProyectos1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextExamen1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jTextProyectos2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextExamen2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButAleatorios))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabPromTareas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabPromPoyectos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextExamen3, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                            .addComponent(jLabPromExamen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabCalif3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabCalif2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabCalif1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabPromCalif, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextAlumno3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextAlumno2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextAsist2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextAsist3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextTareas3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(jTextProyectos3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextTareas2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(206, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButCalcular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButBorrar))
                    .addComponent(jLabMejor, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextExamen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextTareas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextAlumno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextAsist1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextProyectos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextAlumno2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextAsist2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextTareas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextExamen2)
                            .addComponent(jTextProyectos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabCalif1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabCalif2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextAlumno3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextAsist3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextTareas3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextExamen3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextProyectos3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabCalif3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabPromAsist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabPromPoyectos, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(jLabPromExamen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(jLabPromCalif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabPromTareas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButCalcular)
                    .addComponent(jButAleatorios)
                    .addComponent(jButBorrar))
                .addGap(18, 18, 18)
                .addComponent(jLabMejor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextAlumno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextAlumno1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAlumno1ActionPerformed

    private void jTextAlumno2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextAlumno2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAlumno2ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextAlumno3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextAlumno3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAlumno3ActionPerformed

    private void jButCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCalcularActionPerformed
        int asist, tareas, proy, examen;
        DecimalFormat f = new DecimalFormat("###.00");
        
        Alumno uno = new Alumno();
        asist = Integer.parseInt(jTextAsist1.getText());
        tareas = Integer.parseInt(jTextTareas1.getText());
        proy = Integer.parseInt(jTextProyectos1.getText());
        examen = Integer.parseInt(jTextExamen1.getText());
        
        uno.setNombre(jTextAlumno1.getText());
        uno.setAsistencias(asist);
        uno.setTareas(tareas);
        uno.setProyectos(proy);
        uno.setExamen(examen);
        
        jLabCalif1.setText(f.format(uno.calificacion()));
        
        Alumno dos = new Alumno(jTextAlumno2.getText(),
                Integer.parseInt(jTextAsist2.getText()),
                Integer.parseInt(jTextTareas2.getText()),
                Integer.parseInt(jTextProyectos2.getText()),
                Integer.parseInt(jTextExamen2.getText()));
        
        jLabCalif2.setText(f.format(dos.calificacion()));
        
        Alumno tres = new Alumno(uno);
        tres.setNombre(jTextAlumno3.getText());
        tres.setAsistencias(Integer.parseInt(jTextAsist3.getText()));
        tres.setTareas(Integer.parseInt(jTextTareas3.getText()));
        tres.setProyectos(Integer.parseInt(jTextProyectos3.getText()));
        tres.setExamen(Integer.parseInt(jTextExamen3.getText()));
        
        jLabCalif3.setText(f.format(tres.calificacion()));
        
        double promAsist,promTareas,promProy,promExamen,promGral;
        
        promAsist = (uno.getAsistencias()+dos.getAsistencias()+tres.getAsistencias())/3.0;
        promTareas = (uno.getTareas()+dos.getTareas()+tres.getTareas())/3.0;
        promProy = (uno.getProyectos()+dos.getProyectos()+tres.getProyectos())/3.0;
        promExamen = (uno.getExamen()+dos.getExamen()+tres.getExamen())/3.0;
        promGral = (uno.calificacion()+dos.calificacion()+tres.calificacion())/3;
        
        jLabPromAsist.setText(f.format(promAsist));
        jLabPromTareas.setText(f.format(promTareas));
        jLabPromPoyectos.setText(f.format(promProy));
        jLabPromExamen.setText(f.format(promExamen));
        jLabPromCalif.setText(f.format(promGral));
        
        String mejor="";
        if(uno.calificacion() > dos.calificacion())
            if(uno.calificacion() > tres.calificacion())
                mejor = uno.getNombre();
        else
            if(dos.calificacion() > tres.calificacion())
                mejor = dos.getNombre();
            else
                mejor = tres.getNombre();
        
        jLabMejor.setText("El mejor alumno es "+mejor);
          
    }//GEN-LAST:event_jButCalcularActionPerformed

    private void jButAleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAleatoriosActionPerformed
        Random azar = new Random();
        
        String []nom = {"Juan","Maria","Pedro","Luis","Diana","Martha","Sofia","Mario","Raul"};
        String []ape = {"Lopez","Perez","Gomez","Ruiz","Mendez","Aguilera","Garcia","Montes","Hernandez"};
        
        jTextAlumno1.setText(nom[azar.nextInt(nom.length)]+" "+ape[azar.nextInt(ape.length)]);
        jTextAlumno2.setText(nom[azar.nextInt(nom.length)]+" "+ape[azar.nextInt(ape.length)]);
        jTextAlumno3.setText(nom[azar.nextInt(nom.length)]+" "+ape[azar.nextInt(ape.length)]);
        
        jTextAsist1.setText(40+azar.nextInt(61)+"");
        jTextAsist2.setText(40+azar.nextInt(61)+"");
        jTextAsist3.setText(40+azar.nextInt(61)+"");
        
        jTextTareas1.setText(40+azar.nextInt(61)+"");
        jTextTareas2.setText(40+azar.nextInt(61)+"");
        jTextTareas3.setText(40+azar.nextInt(61)+"");
        
        jTextProyectos1.setText(40+azar.nextInt(61)+"");
        jTextProyectos2.setText(40+azar.nextInt(61)+"");
        jTextProyectos3.setText(40+azar.nextInt(61)+"");
        
        jTextExamen1.setText(40+azar.nextInt(61)+"");
        jTextExamen2.setText(40+azar.nextInt(61)+"");
        jTextExamen3.setText(40+azar.nextInt(61)+"");
        
    }//GEN-LAST:event_jButAleatoriosActionPerformed

    private void jButBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButBorrarActionPerformed
        jTextAlumno1.setText("");
        jTextAlumno2.setText("");
        jTextAlumno3.setText("");
        
        jTextAsist1.setText("");
        jTextAsist2.setText("");
        jTextAsist3.setText("");
        
        jTextTareas1.setText("");
        jTextTareas2.setText("");
        jTextTareas3.setText("");
        
        jTextProyectos1.setText("");
        jTextProyectos2.setText("");
        jTextProyectos3.setText("");
        
        jTextExamen1.setText("");
        jTextExamen2.setText("");
        jTextExamen3.setText("");
        
        jLabCalif1.setText("");
        jLabCalif2.setText("");
        jLabCalif3.setText("");
        
        jLabPromAsist.setText("");
        jLabPromTareas.setText("");
        jLabPromExamen.setText("");
        jLabPromPoyectos.setText("");


    }//GEN-LAST:event_jButBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JframePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JframePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JframePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JframePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JframePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButAleatorios;
    private javax.swing.JButton jButBorrar;
    private javax.swing.JButton jButCalcular;
    private javax.swing.JLabel jLabCalif1;
    private javax.swing.JLabel jLabCalif2;
    private javax.swing.JLabel jLabCalif3;
    private javax.swing.JLabel jLabMejor;
    private javax.swing.JLabel jLabPromAsist;
    private javax.swing.JLabel jLabPromCalif;
    private javax.swing.JLabel jLabPromExamen;
    private javax.swing.JLabel jLabPromPoyectos;
    private javax.swing.JLabel jLabPromTareas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextAlumno1;
    private javax.swing.JTextField jTextAlumno2;
    private javax.swing.JTextField jTextAlumno3;
    private javax.swing.JTextField jTextAsist1;
    private javax.swing.JTextField jTextAsist2;
    private javax.swing.JTextField jTextAsist3;
    private javax.swing.JTextField jTextExamen1;
    private javax.swing.JTextField jTextExamen2;
    private javax.swing.JTextField jTextExamen3;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextProyectos1;
    private javax.swing.JTextField jTextProyectos2;
    private javax.swing.JTextField jTextProyectos3;
    private javax.swing.JTextField jTextTareas1;
    private javax.swing.JTextField jTextTareas2;
    private javax.swing.JTextField jTextTareas3;
    // End of variables declaration//GEN-END:variables
}
